"""Systemd service unit management for codex-adapter.

Generates, installs, and removes the systemd unit file.
"""

from __future__ import annotations

import getpass
import os
import shutil
import subprocess
from pathlib import Path
from textwrap import dedent

from rich.console import Console

console = Console()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

UNIT_NAME = "codex-adapter"
UNIT_FILE = Path(f"/etc/systemd/system/{UNIT_NAME}.service")


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

def is_systemd_available() -> bool:
    """Check if systemd is available on this system."""
    return shutil.which("systemctl") is not None


def is_unit_installed() -> bool:
    """Check if the codex-adapter systemd unit is installed."""
    return UNIT_FILE.exists()


def is_active() -> bool:
    """Check if the systemd service is currently active."""
    if not is_unit_installed():
        return False
    r = subprocess.run(
        ["systemctl", "is-active", "--quiet", UNIT_NAME],
        capture_output=True,
    )
    return r.returncode == 0


# ---------------------------------------------------------------------------
# Unit generation
# ---------------------------------------------------------------------------

def generate_unit(
    user: str,
    project_dir: str | Path,
    venv_bin: str | Path,
    env_file: str | Path,
    preset: str,
    port: int,
) -> str:
    """Generate the systemd unit file content.

    This is a pure function — returns a string, no side effects.
    """
    return dedent(f"""\
        [Unit]
        Description=Codex Adapter Proxy Service
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=simple
        User={user}
        Group={user}

        # Environment file (generated by codex-adapter configure)
        EnvironmentFile={env_file}

        # Working directory
        WorkingDirectory={project_dir}

        # Start command
        ExecStart={venv_bin}/codex-adapter start --preset {preset} --port {port}

        # Restart policy
        Restart=on-failure
        RestartSec=5
        StartLimitBurst=5
        StartLimitIntervalSec=60

        # Logging
        StandardOutput=journal
        StandardError=journal
        SyslogIdentifier=codex-adapter

        # Security hardening
        NoNewPrivileges=yes
        ProtectSystem=strict
        ProtectHome=read-only
        ReadWritePaths={project_dir} /tmp
        PrivateTmp=yes

        # Resource limits
        LimitNOFILE=65536

        [Install]
        WantedBy=multi-user.target
    """)


# ---------------------------------------------------------------------------
# Install / uninstall
# ---------------------------------------------------------------------------

def install_unit(
    project_dir: str | Path,
    preset: str = "deepseek",
    port: int = 4000,
    env_file: str | Path | None = None,
) -> Path:
    """Render and install the systemd unit file.

    Requires sudo privileges. Returns the path of the installed file.
    """
    if not is_systemd_available():
        raise RuntimeError("systemd is not available on this system")

    project_dir = Path(project_dir)
    venv_bin = project_dir / ".venv" / "bin"
    user = getpass.getuser()
    env_file = env_file or (Path.home() / ".codex-adapter.env")

    content = generate_unit(
        user=user,
        project_dir=project_dir,
        venv_bin=venv_bin,
        env_file=env_file,
        preset=preset,
        port=port,
    )

    console.print("[blue]Installing systemd service ...[/]")

    # Write unit file via sudo tee
    proc = subprocess.run(
        ["sudo", "tee", str(UNIT_FILE)],
        input=content,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"Failed to write unit file: {proc.stderr}")

    # Reload and enable
    subprocess.run(["sudo", "systemctl", "daemon-reload"], check=True)
    subprocess.run(["sudo", "systemctl", "enable", UNIT_NAME], check=True)

    console.print(f"[green]Systemd service installed and enabled:[/] {UNIT_FILE}")
    console.print(f"[dim]Start with: sudo systemctl start {UNIT_NAME}[/]")

    return UNIT_FILE


def uninstall_unit() -> None:
    """Stop, disable, and remove the systemd unit file."""
    if not is_unit_installed():
        console.print("[yellow]Systemd service is not installed[/]")
        return

    console.print("[blue]Uninstalling systemd service ...[/]")

    # Stop if running
    if is_active():
        subprocess.run(["sudo", "systemctl", "stop", UNIT_NAME], check=False)

    # Disable and remove
    subprocess.run(["sudo", "systemctl", "disable", UNIT_NAME], check=False)
    subprocess.run(["sudo", "rm", "-f", str(UNIT_FILE)], check=True)
    subprocess.run(["sudo", "systemctl", "daemon-reload"], check=True)

    console.print("[green]Systemd service uninstalled[/]")


def start_via_systemd() -> None:
    """Start the service via systemd."""
    subprocess.run(["sudo", "systemctl", "start", UNIT_NAME], check=True)
    console.print(f"[green]Service started via systemd[/]")


def stop_via_systemd() -> None:
    """Stop the service via systemd."""
    subprocess.run(["sudo", "systemctl", "stop", UNIT_NAME], check=True)
    console.print(f"[green]Service stopped via systemd[/]")


def show_journal(follow: bool = False, lines: int = 50) -> None:
    """Show systemd journal logs for the service."""
    cmd = ["journalctl", "-u", UNIT_NAME, "--no-pager"]
    if follow:
        cmd.append("-f")
    else:
        cmd.extend(["-n", str(lines)])

    try:
        subprocess.run(cmd)
    except KeyboardInterrupt:
        pass
